name: "PROD DEPLOY"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: "prod"
      aws-assume-role-arn: "arn:aws:iam::046959477383:role/github-actions-caioalbert-pipeline"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "caioalbert-sa-east-1-terraform-statefile"
      aws-lock-dynamodb-table: "caioalbert-sa-east-1-terraform-lock"